// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzGAzAhtdIMl_Uf_EYQSUHB6WlSPAJCRY',
    appId: '1:61134191351:web:487e9adf6e27755bad31f2',
    messagingSenderId: '61134191351',
    projectId: 'store-62668',
    authDomain: 'store-62668.firebaseapp.com',
    storageBucket: 'store-62668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_rNCVyAlEb5xIbyOgdTWTiT5x-lKOMMg',
    appId: '1:61134191351:android:56512a32a0241219ad31f2',
    messagingSenderId: '61134191351',
    projectId: 'store-62668',
    storageBucket: 'store-62668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5EnpfvWwoqDNoZmX_keTcljKCEMD7tk4',
    appId: '1:61134191351:ios:49283c69b6f23cd3ad31f2',
    messagingSenderId: '61134191351',
    projectId: 'store-62668',
    storageBucket: 'store-62668.appspot.com',
    iosClientId: '61134191351-94djdrm1cgdkvba8j0gglapdidoulopu.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAppAdvanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5EnpfvWwoqDNoZmX_keTcljKCEMD7tk4',
    appId: '1:61134191351:ios:49283c69b6f23cd3ad31f2',
    messagingSenderId: '61134191351',
    projectId: 'store-62668',
    storageBucket: 'store-62668.appspot.com',
    iosClientId: '61134191351-94djdrm1cgdkvba8j0gglapdidoulopu.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAppAdvanced',
  );
}
